import { CensusTract } from '../../types';

/**
 * Legacy Dataset V1: 12 tractos censales sintéticos demostrativos.
 * NOTA: Aislado en V2 como referencia histórica. No alimenta la interfaz activa V2.
 */
export const SYNTHETIC_TRACTS_V1: CensusTract[] = [
  {
    geoid: 'DEMO-001',
    nombre: 'Distrito Norte - Los Pinos',
    poblacion: 5420,
    ingresoMedio: 68500,
    prevalenciaDiabetesInicial: 8.4,
    indiceAccesoSaludable: 78,
    densidadComidaRapida: 32,
    accesoVehiculo: 88,
    vulnerabilidad: 'Baja',
    coordenadaFila: 0,
    coordenadaColumna: 0,
    zonaUrbana: 'Residencial Norte'
  },
  {
    geoid: 'DEMO-002',
    nombre: 'Valle Central Universitario',
    poblacion: 7100,
    ingresoMedio: 54200,
    prevalenciaDiabetesInicial: 9.9,
    indiceAccesoSaludable: 64,
    densidadComidaRapida: 58,
    accesoVehiculo: 62,
    vulnerabilidad: 'Media',
    coordenadaFila: 0,
    coordenadaColumna: 1,
    zonaUrbana: 'Campus y Residencial Mixto'
  },
  {
    geoid: 'DEMO-003',
    nombre: 'Parque Industrial Este',
    poblacion: 4350,
    ingresoMedio: 36800,
    prevalenciaDiabetesInicial: 13.8,
    indiceAccesoSaludable: 38,
    densidadComidaRapida: 72,
    accesoVehiculo: 48,
    vulnerabilidad: 'Alta',
    coordenadaFila: 0,
    coordenadaColumna: 2,
    zonaUrbana: 'Periferia Industrial'
  },
  {
    geoid: 'DEMO-004',
    nombre: 'Ribera Nororiental',
    poblacion: 3890,
    ingresoMedio: 31200,
    prevalenciaDiabetesInicial: 15.2,
    indiceAccesoSaludable: 26,
    densidadComidaRapida: 82,
    accesoVehiculo: 39,
    vulnerabilidad: 'Alta',
    coordenadaFila: 0,
    coordenadaColumna: 3,
    zonaUrbana: 'Asentamiento Fluvial'
  },
  {
    geoid: 'DEMO-005',
    nombre: 'Colinas del Oeste',
    poblacion: 6200,
    ingresoMedio: 79400,
    prevalenciaDiabetesInicial: 7.6,
    indiceAccesoSaludable: 84,
    densidadComidaRapida: 24,
    accesoVehiculo: 92,
    vulnerabilidad: 'Baja',
    coordenadaFila: 1,
    coordenadaColumna: 0,
    zonaUrbana: 'Residencial Alta Densidad'
  },
  {
    geoid: 'DEMO-006',
    nombre: 'Centro Histórico y Comercial',
    poblacion: 8650,
    ingresoMedio: 48900,
    prevalenciaDiabetesInicial: 11.5,
    indiceAccesoSaludable: 55,
    densidadComidaRapida: 86,
    accesoVehiculo: 51,
    vulnerabilidad: 'Media',
    coordenadaFila: 1,
    coordenadaColumna: 1,
    zonaUrbana: 'Núcleo Central y Servicios'
  },
  {
    geoid: 'DEMO-007',
    nombre: 'Barrio Estación Ferroviaria',
    poblacion: 5980,
    ingresoMedio: 41500,
    prevalenciaDiabetesInicial: 12.7,
    indiceAccesoSaludable: 42,
    densidadComidaRapida: 76,
    accesoVehiculo: 56,
    vulnerabilidad: 'Media',
    coordenadaFila: 1,
    coordenadaColumna: 2,
    zonaUrbana: 'Corredor de Tránsito'
  },
  {
    geoid: 'DEMO-008',
    nombre: 'San Pedro Oriental',
    poblacion: 4900,
    ingresoMedio: 29800,
    prevalenciaDiabetesInicial: 16.1,
    indiceAccesoSaludable: 22,
    densidadComidaRapida: 88,
    accesoVehiculo: 41,
    vulnerabilidad: 'Alta',
    coordenadaFila: 1,
    coordenadaColumna: 3,
    zonaUrbana: 'Vivienda Social Este'
  },
  {
    geoid: 'DEMO-009',
    nombre: 'Altos del Suroeste',
    poblacion: 5120,
    ingresoMedio: 62400,
    prevalenciaDiabetesInicial: 8.9,
    indiceAccesoSaludable: 72,
    densidadComidaRapida: 36,
    accesoVehiculo: 84,
    vulnerabilidad: 'Baja',
    coordenadaFila: 2,
    coordenadaColumna: 0,
    zonaUrbana: 'Residencial Periférico Sur'
  },
  {
    geoid: 'DEMO-010',
    nombre: 'Alameda del Sur',
    poblacion: 6780,
    ingresoMedio: 51000,
    prevalenciaDiabetesInicial: 10.8,
    indiceAccesoSaludable: 60,
    densidadComidaRapida: 62,
    accesoVehiculo: 68,
    vulnerabilidad: 'Media',
    coordenadaFila: 2,
    coordenadaColumna: 1,
    zonaUrbana: 'Comercial y Residencial'
  },
  {
    geoid: 'DEMO-011',
    nombre: 'Nuevo Horizonte Sur',
    poblacion: 7450,
    ingresoMedio: 38200,
    prevalenciaDiabetesInicial: 13.4,
    indiceAccesoSaludable: 45,
    densidadComidaRapida: 69,
    accesoVehiculo: 54,
    vulnerabilidad: 'Alta',
    coordenadaFila: 2,
    coordenadaColumna: 2,
    zonaUrbana: 'Expansión Urbana'
  },
  {
    geoid: 'DEMO-012',
    nombre: 'Villa Esperanza',
    poblacion: 4200,
    ingresoMedio: 27500,
    prevalenciaDiabetesInicial: 15.9,
    indiceAccesoSaludable: 25,
    densidadComidaRapida: 84,
    accesoVehiculo: 35,
    vulnerabilidad: 'Alta',
    coordenadaFila: 2,
    coordenadaColumna: 3,
    zonaUrbana: 'Sector Periférico Vulnerable'
  }
];
